### ISSUE TITLE
Make a runtime

### ISSUE THREAD

**Issue by K1nzy** [Dev1nee/discord.css#7]
we wont approve the full project until there is a runtime

**Comment by Dev1nee** [comment]
calm down there pal,
I've got some stuff in the works i think you'd like.

**Comment by MininMobile** [comment]
(he's reusing the discord.bat's runtime as we speak 😉 )

**Comment by Dev1nee** [comment]
Fight me

**Comment by MininMobile** [comment]
Nothing...

**Comment by K1nzy** [comment]
Old conversation, the project is being re-write
