### ISSUE TITLE
Location is spelt wrong

### ISSUE THREAD

**Issue by ohlookitsderpy** [Dev1nee/discord.css#9]
in both files and the readme

**Comment by Dev1nee** [comment]
I am terribly sorry for your inconvenience.

If you could please specify the directory and file for this problem we will get straight to fixing this issue for you!
Thank you for your support and have a nice evening,
-Dev!ne

**Comment by K1nzy** [comment]
The project has been already updated and we donʻt use the `Location` package anymore.
